-- Step 1: Create User
CREATE USER yumxpress IDENTIFIED BY foodie;

-- Step 2: Grant Permissions
GRANT resource, connect TO yumxpress;

-- Step 3: Connect to User
-- This is for reference. Execute manually in SQL*Plus or Oracle SQL Developer.
-- CONNECT yumxpress/foodie;

-- Step 4: Create COMPANIES Table
CREATE TABLE COMPANIES (
    COMPANY_ID VARCHAR2(10) CONSTRAINT COMPANIES_PK PRIMARY KEY,
    COMPANY_NAME VARCHAR2(100) CONSTRAINT CMP_UNQ_NAME UNIQUE,
    OWNER_NAME VARCHAR2(50),
    PASSWORD VARCHAR2(20),
    STATUS VARCHAR2(50),
    EMAIL_ID VARCHAR2(100) CONSTRAINT CMP_UNQ_EM_ID UNIQUE,
    SECURITY_KEY VARCHAR2(100)
);

-- Step 5: Create PRODUCTS Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR2(10) CONSTRAINT PRODUCTS_PK PRIMARY KEY,
    COMPANY_ID VARCHAR2(10) CONSTRAINT PD_FK_CMP_ID REFERENCES COMPANIES(COMPANY_ID),
    PRODUCT_NAME VARCHAR2(50),
    PRODUCT_PRICE NUMBER(7,2),
    PRODUCT_IMAGE BLOB
);

-- Step 6: Create STAFF Table
CREATE TABLE STAFF (
    STAFF_ID VARCHAR2(10) CONSTRAINT STAFFS_PK PRIMARY KEY,
    COMPANY_ID VARCHAR2(30) CONSTRAINT STF_FK_CMP_ID REFERENCES COMPANIES(COMPANY_ID),
    EMAIL_ID VARCHAR2(30) CONSTRAINT STF_NN_EMID NOT NULL,
    PASSWORD VARCHAR2(30) CONSTRAINT STF_NN_PWD NOT NULL,
    STAFF_NAME VARCHAR2(50)
);

-- Step 7: Create CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR2(10) CONSTRAINT CUSTOMERS_PK PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50),
    EMAIL_ID VARCHAR2(30) CONSTRAINT CUSTOMERS_EM_NN NOT NULL,
    PASSWORD VARCHAR2(20),
    MOBILE_NO VARCHAR2(10),
    ADDRESS VARCHAR2(150)
);

-- Step 8: Create ORDERS Table
CREATE TABLE ORDERS (
    ORDER_ID VARCHAR2(10) CONSTRAINT ORDERS_PK PRIMARY KEY,
    PRODUCT_ID VARCHAR2(10) CONSTRAINT ORD_FK_PID REFERENCES PRODUCTS(PRODUCT_ID),
    CUSTOMER_ID VARCHAR2(10) CONSTRAINT ORD_FK_CMTR_ID REFERENCES CUSTOMERS(CUSTOMER_ID),
    STAFF_ID VARCHAR2(10) CONSTRAINT ORD_FK_STF_ID REFERENCES STAFF(STAFF_ID),
    REVIEW VARCHAR2(200),
    STATUS VARCHAR2(50),
    COMPANY_ID VARCHAR2(20) CONSTRAINT ORD_FK_CMP_ID REFERENCES COMPANIES(COMPANY_ID),
    OTP NUMBER(10)
);
